# Site settings
title: JaeKeun-Lee
baseurl: "/ap"
url: "https://jaekeun-lee.github.io/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: JaeKeun Lee
  desc: Java & Backend Junior Developer
  email: ljg960730@naver.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 96gllee 
  flickr:
  github: Jaekeun-Lee 
  google_plus:
  instagram: 96.glee
  keybase:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"


# # social
# social:
#   email: true
#   behance:
#   bitbucket:
#   dribbble:
#   facebook: Test
#   flickr:
#   github: kssim
#   google_plus:
#   instagram:
#   keybase:
#   linkedin: https://www.linkedin.com/in/kssim/ 

