# Site settings
title: 이재근 | 서버 벡엔드 엔지니어
nav_title: JaeKeun-Lee
baseurl: 
url: "https://jaekeun-lee.github.io/"
google_analytics: "G-KMV048VNRD"
last_modified_at: 2024.03.13

# Author
author:
  name: JaeKeun Lee
  desc: Backend Junior Developer
  email: ljg960730@naver.com
  selfie: assets/img/profile.jpg

# social
social:
  재: true
  behance:
  bitbucket:
  dribbble:
  facebook: 96gllee 
  flickr:
  github: Jaekeun-Lee 
  google_plus:
  instagram: 96.glee
  keybase:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  tistory: ljg960730
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
  - "screenshot.png"

