# Site
repository: Jaekeun-Lee/Jaekeun-Lee.github.io
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이재근
title: Java & Backend Developer
email: jacklee730@naver.com
website: https://ljg960730.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Jaekeun-Lee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: 96gllee
# flickr_username: jekyll
instagram_username: 96.glee
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  열정적으로 도전하는 개발자 이재근입니다.


  웹을 통해 사람을 연결하고 문제를 해결, 불편함을 개선하는 매력에 빠져 웹 개발의 길을 걷고 있습니다.
  Java를 시작으로 사회와 코딩을 더욱 폭 넓게 경험하는 사회 새싹 주니어 개발자 입니다.
  

  <mark>#도전</mark>  <mark>#소통</mark>  <mark>#신뢰</mark>


content:
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        quote: >
          개발 과정 중 주로 사용했던 가장 익숙한 기술들 입니다.
        description: | # this will include new lines to allow paragraphs
          <h4 style="text-align:center">
            <mark>Java</mark>  <mark>SpringMVC</mark>  <mark>Springboot</mark>  <mark>jsp</mark>  <mark>Oracle</mark>  
          </h4>
          <hr>
      - layout: top-middle
        additional_links:
          - title: 보유기술 숙련도 기술 페이지
            icon: fa fa-th-list
            url: https://www.notion.so/b3417dfd21544aa7b9b7e2f7f585e360
        quote: >
          프로젝트 진행 중 경험했던 기술들 입니다.
          <a href="https://www.notion.so/b3417dfd21544aa7b9b7e2f7f585e360" style="color:#000; font-style:normal;"> <br/> <span style="color:#ff4040">자세한 기술 숙련도</span>는 아이콘 또는 이 문장 클릭을 통해 확인 가능합니다! </a>            
        
      - layout: top-left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * Java, Python, Php, NodeJS
          * Spring Boot, Spring MVC, Spring Batch, Spring Security, Spring Data JPA
          * JPA, Querydsl, Hibernate
          * Junit4/5
          * Gradle, Maven
          * Eclipse, IntelliJ, Visual Studio Code
      
      - layout: top-left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          * HTML5, CSS3
          * Javascript(ES5, ES6), jQuery
          * Vue.js

      - layout: top-left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          * Oracle, MySQL, MariaDB
          * Jenkins, TravisCI, AWS Code Deploy
          * RDS (MariaDB), S3, EC2
          * Tomcat


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag