items:
  - name: Matchnow Project
    company: 이투스 교육 (Etoos) <br/> - 회원 웹솔루션 개발팀
    date: 2023.04 ~ 2023.08
    title: 대학생 멘토와 입시생들을 연결하는 온라인 매칭 플랫폼.<br/> <br/>한국과 인도 2개국 베타 버전 오픈 후 운영 및 추가 기능 개발.
    link:
      - name: Matchnow Korea
        url: https://www.matchnow.co.kr
      - name: Matchnow India
        url: https://www.matchnow.in
    doing:
      - title: 주 담당업무
        content:
          - 매칭 서비스 제공에 필요한 BFF 개발
          - 플랫폼(Web, Android, iOS) 대응 프론트 페이지 개발 및 유지보수
      - title: 담당업무 상세
        content:
          - Quiz & Poll 기능 개발
          - 상품 페이지, 이벤트 페이지 개발 및 유지보수
          - 회원 정보, 인증/인가 서비스 개발 및 운영
          - 통합 회원 프로젝트를 통해 7개의 교육 서비스 회원 통합
          - 글로벌(인도) 서비스 서비스 개발 및 운영
          - Admin 프로젝트의 상담 신청서 관리 및 매칭 관리 페이지 및 API 구현
          - 이미지 ↔ pdf 변환 기능을 제공하기 위한 마이크로 서비스 설계 및 개발
          - 팀 내 서비스에서 공통으로 사용하는 메시징 서비스, 알림 서비스를 간단히 연동할 수 있도록 공통 모듈화 작업
          - AWS SNS 메시지 발행을 위한 sns-publish-client 모듈, 메일과 SMS 전송을 위한 sender 모듈 2개의 공통 모듈을 구성하여 프로젝트 적용
          - 매칭 및 예약 서비스 제공에 필요한 BFF API 개발
          - 회원 관리(휴면, 탈퇴), 상품 관리(쿠폰) 비즈니스 로직을 포함한 프로시저를 REST API로 전환
          - MSSQL 스케줄러를 통해 처리되던 프로시저를 Spring Batch로 전환

    skill:
      - Java
      - Spring Boot
      - JPA
      - Mybatis
      - MySQL
      - Redis

  - name: Matchnow Project
    company: 이투스 교육 (Etoos) <br/> - 회원 웹솔루션 개발팀
    date: 2023.04 ~ 2023.08
    title: 대학생 멘토와 입시생들을 연결하는 온라인 매칭 플랫폼.
    link:
      - name: Matchnow India
        url: https://www.matchnow.in
    doing:
      - title: 주 담당업무
        content:
          - 회원 정보 관리 및 매칭 서비스 제공에 필요한 BFF 개발
          - 플랫폼(Web, Android, iOS) 대응 프론트 페이지 개발 및 유지보수
      - title: 담당업무 상세
        content:
          - 서비스 운영에 필요한 페이지(상품, 이벤트 페이지) 개발 및 유지보수
          - <a href="https://docs.pagecall.com/introduction" target="_blank" style="color:#007bff;">Pagecall API</a>를 이용하여 실시간 Quiz & Poll 기능 개발
          - 회원 정보, 인증/인가 서비스 개발 및 운영
          - 통합 회원 프로젝트를 통해 7개의 교육 서비스 회원 통합
          - 글로벌(인도) 서비스 서비스 개발 및 운영
          - Admin 프로젝트의 상담 신청서 관리 및 매칭 관리 페이지 및 API 구현
          - 이미지 ↔ pdf 변환 기능을 제공하기 위한 마이크로 서비스 설계 및 개발
          - 팀 내 서비스에서 공통으로 사용하는 메시징 서비스, 알림 서비스를 간단히 연동할 수 있도록 공통 모듈화 작업
          - AWS SNS 메시지 발행을 위한 sns-publish-client 모듈, 메일과 SMS 전송을 위한 sender 모듈 2개의 공통 모듈을 구성하여 프로젝트 적용
          - 매칭 및 예약 서비스 제공에 필요한 BFF API 개발
          - 회원 관리(휴면, 탈퇴), 상품 관리(쿠폰) 비즈니스 로직을 포함한 프로시저를 REST API로 전환
          - MSSQL 스케줄러를 통해 처리되던 프로시저를 Spring Batch로 전환

    skill:
      - Java
      - Spring Boot
      - JPA
      - Mybatis
      - MySQL
      - Redis
